name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has permission to push commits
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run main.py
      - name: Run main.py
        run: python main.py

      # Commit and push the model back to the repository
      - name: Save the model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add models/* 
          git commit -m "Update trained model" || echo "No changes to commit"
          git push origin main
